fix: Export missing type `AnimationConfig`
Some open-source and largely used libraries such as nivo directly bind to the types being declared by `@react-pring/core` in some of their code.

For instance in nivo, the following code:

```ts
import { SpringValues } from '@react-spring/web'

//...
export interface NodeProps<Datum extends object> {
    //...
    animatedProps: SpringValues<NodeAnimatedProps>
    //...
}
```

Implicitely force nivo to be able to reference parts of the typings of `@react-spring/core` into their d.ts files if they want to be able to publish their package. It basiaclly results into `Partial<import("@react-spring/core").AnimationConfig>` in the produced d.ts at some point. And as a consequence TypeScript complains with the error `error TS4023: Exported variable 'htmlDefaultProps' has or is using name 'AnimationConfig' from external module "/tmp/9a4cf066/node_modules/@react-spring/core/dist/index" but cannot be named.`.

The proposed change exposes `AnimationConfig` as a type, meaning we still don't expose the class, just its type. It would help into making nivo able to support recent version of `@react-spring/*`. See related issue on nivo's side: https://github.com/plouc/nivo/pull/2280